from __future__ import annotations

import re
from pathlib import Path

from reverse_collector.errors import ConfigurationError


def create_plugin_skeleton(name: str, root: str | Path = "plugins") -> Path:
    if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
        raise ConfigurationError("plugin name must match [a-z][a-z0-9_]*")
    root_path = Path(root).resolve()
    package = root_path / name
    if package.exists():
        raise ConfigurationError(f"plugin directory already exists: {package}")
    root_path.mkdir(parents=True, exist_ok=True)
    init = root_path / "__init__.py"
    if not init.exists():
        init.write_text('"""Local reverse-collector plugins."""\n', encoding="utf-8")
    package.mkdir()
    class_name = "".join(part.capitalize() for part in name.split("_")) + "Plugin"
    (package / "__init__.py").write_text(
        f"from plugins.{name}.plugin import {class_name}\n\n__all__ = [\"{class_name}\"]\n",
        encoding="utf-8",
    )
    (package / "plugin.py").write_text(_PLUGIN_TEMPLATE.format(name=name, class_name=class_name), encoding="utf-8")
    (package / "README.md").write_text(_README_TEMPLATE.format(name=name, class_name=class_name), encoding="utf-8")
    (package / "task.example.toml").write_text(_TASK_TEMPLATE.format(name=name, class_name=class_name), encoding="utf-8")
    return package


_PLUGIN_TEMPLATE = '''from __future__ import annotations

from typing import Any

from reverse_collector.context import RunContext
from reverse_collector.errors import PluginError
from reverse_collector.models import RequestSpec, ResponseData, TaskConfig
from reverse_collector.plugin import ApiCollectorPlugin, PageResult


class {class_name}(ApiCollectorPlugin):
    name = "{name}"
    description = "TODO: describe the platform dataset"

    async def setup(self, context: RunContext, task: TaskConfig) -> None:
        # For browser-authenticated APIs, open the correct origin here and verify
        # login with a low-cost probe. Never hard-code credentials or cookies.
        pass

    async def refresh_auth(self, context: RunContext, task: TaskConfig) -> bool:
        # Refresh tokens/cookies once and return True. Return False when manual
        # login is required and the task is not interactive.
        return False

    async def first_request(
        self,
        context: RunContext,
        task: TaskConfig,
        checkpoint: dict[str, Any] | None,
    ) -> RequestSpec:
        cursor = (checkpoint or {{}}).get("cursor")
        return RequestSpec(
            endpoint_id="{name}.dataset",
            method="GET",
            url=str(task.parameters["api_url"]),
            params={{"cursor": cursor}} if cursor else {{}},
            metadata={{"expect_json": True}},
        )

    async def parse_page(
        self,
        context: RunContext,
        task: TaskConfig,
        request: RequestSpec,
        response: ResponseData,
    ) -> PageResult:
        payload = response.json()
        if not isinstance(payload, dict) or not isinstance(payload.get("rows"), list):
            raise PluginError("response schema changed: expected an object with rows[]")
        cursor = payload.get("next_cursor")
        return PageResult(
            records=payload["rows"],
            next_request=None if not cursor else RequestSpec(
                endpoint_id="{name}.dataset",
                method="GET",
                url=str(task.parameters["api_url"]),
                params={{"cursor": cursor}},
                metadata={{"expect_json": True}},
            ),
            checkpoint={{"cursor": cursor}},
            done=not bool(cursor),
        )
'''

_README_TEMPLATE = '''# {name}

Platform-specific adapter generated by `reverse-collector new-plugin`.

1. Run discovery mode against a page your account is authorized to access.
2. Document the endpoint, auth fields, pagination, and response schema.
3. Implement login probing, request building, strict parsing, and auth refresh.
4. Add offline parser tests using a redacted response fixture.

Plugin reference: `plugins.{name}.plugin:{class_name}`
'''

_TASK_TEMPLATE = '''[task]
name = "{name}_daily"
plugin = "plugins.{name}.plugin:{class_name}"
dataset = "replace_me"

[task.parameters]
api_url = "https://example.invalid/api/data"
schema_version = "1"

[transport]
mode = "auto"
order = ["http", "browser_fetch"]

[browser]
user_data_dir = "profiles/{name}/default"
start_url = "https://example.invalid/"

[[outputs]]
type = "jsonl"
path = "output/{name}/{{date}}.jsonl"
'''

